services:
  backend:
    image: hashinikavindya/movie-watchlist-backend:latest
    pull_policy: always
    container_name: movie-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET:-mySecret}
      - TMDB_API_KEY=${TMDB_API_KEY}
    restart: unless-stopped

  frontend:
    image: hashinikavindya/movie-watchlist-frontend:latest
    pull_policy: always
    container_name: movie-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

