services:
  mongo:
    image: mongo:6.0
    container_name: movie-mongo
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    image: hashinikavindya/movie-watchlist-backend:latest
    pull_policy: always
    container_name: movie-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/moviewatchlist
      - JWT_SECRET=${JWT_SECRET:-mySecret}
      - TMDB_API_KEY=${TMDB_API_KEY}
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: hashinikavindya/movie-watchlist-frontend:latest
    pull_policy: always
    container_name: movie-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
